In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.6.0+cu124


In [2]:
#scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
#vector

vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX.ndim

2

In [11]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,4,5],
                      [3,2,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [3, 2, 4]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
a=torch.tensor([[[[[[[[[[[[[1,2,3,4],
 [8,9,9,8]]]]]]]]]]]]])
a

tensor([[[[[[[[[[[[[1, 2, 3, 4],
                   [8, 9, 9, 8]]]]]]]]]]]]])

In [14]:
a.shape

torch.Size([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4])

In [15]:
a.ndim

13

Create a random tensor

In [16]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8033, 0.8822, 0.8095, 0.1417],
        [0.9166, 0.6805, 0.4199, 0.3622],
        [0.1193, 0.0319, 0.1759, 0.9169]])

In [17]:
# create a randome tensor with similar shape to an image tensor
randome_image_size_tensor=torch.rand(size=(3,224,224))
print(randome_image_size_tensor.shape,"dimension = ",randome_image_size_tensor.ndim)

torch.Size([3, 224, 224]) dimension =  3


In [18]:
random_tensor1=torch.rand(3,4,3)
print(random_tensor1)
print(random_tensor1.ndim)

tensor([[[0.5013, 0.9230, 0.5969],
         [0.0420, 0.7484, 0.1193],
         [0.1251, 0.6922, 0.3553],
         [0.5639, 0.1827, 0.6020]],

        [[0.4453, 0.8019, 0.1062],
         [0.0944, 0.8563, 0.1783],
         [0.0284, 0.1692, 0.7215],
         [0.1122, 0.6626, 0.8879]],

        [[0.4732, 0.9456, 0.8231],
         [0.0789, 0.4552, 0.9196],
         [0.9771, 0.4184, 0.6395],
         [0.1067, 0.1637, 0.6156]]])
3


Zeros and Ones Tensor

In [19]:
zeros=torch.zeros(size=(4,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
zeros*random_tensor1

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [21]:
#creating a tensor of all ones
ones=torch.ones(size=(3,3,2,3,4))
ones

tensor([[[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

         

In [22]:
ones.dtype

torch.float32

Creating a range of tensors and tensor_like

In [23]:
#use torch .rande()
one_2_ten=torch.arange(2,11,3)
one_2_ten

tensor([2, 5, 8])

In [24]:
#creating tensors like

ten_zeros=torch.zeros_like(input=one_2_ten)
ten_zeros

tensor([0, 0, 0])

In [25]:
ten_one=torch.ones_like(input=ten_zeros)
ten_one

tensor([1, 1, 1])

Tensor Data type

In [26]:
#float 32 tensor
float_32_tensor=torch.tensor([1,2,3,3,423],
                             dtype=torch.float16,
                             device="cpu",
                             requires_grad=False)
float_32_tensor

tensor([  1.,   2.,   3.,   3., 423.], dtype=torch.float16)

In [27]:
unsinged_integer=torch.tensor([1,2,3,4,5,67,8],
                              dtype=torch.uint8,
                              device='cpu',
                              requires_grad=False)
unsinged_integer

tensor([ 1,  2,  3,  4,  5, 67,  8], dtype=torch.uint8)

In [28]:
unsinged_integer.dtype

torch.uint8

In [29]:
one_ten=torch.ones_like(input=torch.arange(0,10))
one_ten

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
tensor_16_float=torch.tensor([1,2,32,430],
                            dtype=torch.float16,
                            device=None,
                            requires_grad=False
                            )

In [31]:
tensor_32_float=torch.tensor([1,2,32,430],
                            dtype=torch.float32,
                            device=None,
                            requires_grad=False
                            )

In [32]:
tensor_16_float*tensor_32_float

tensor([1.0000e+00, 4.0000e+00, 1.0240e+03, 1.8490e+05])

In [33]:
integer_tensor=torch.tensor([1,23,2,212],
                            dtype=torch.int32)

In [34]:
integer_tensor*tensor_16_float

tensor([ 1., 46., 64., inf], dtype=torch.float16)

In [35]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0351, 0.6895, 0.9909, 0.9278],
        [0.2275, 0.8061, 0.4881, 0.3141],
        [0.9847, 0.0871, 0.8332, 0.4313]])

In [36]:
some_tensor=some_tensor.type(torch.float16)

In [37]:
print(f"Data Type of the tensor is:-{some_tensor.dtype}")
print(f"Device of the Tensor is :-{some_tensor.device}")
print(f"Size of the tensor:-{some_tensor.size()}")
print(f"Dimension of the tensor is:-{some_tensor.ndim}")

Data Type of the tensor is:-torch.float16
Device of the Tensor is :-cpu
Size of the tensor:-torch.Size([3, 4])
Dimension of the tensor is:-2


In [38]:
device=torch.device("cuda")

In [39]:
#error because we are using cpu insted of gpu "cuda is a gpu device not a cpu device"

some_tensor=some_tensor.to(device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [40]:
some_tensor.device

device(type='cpu')

In [41]:
#matrix multiplocation
%%time
mat1=torch.tensor([[1,2,3],
                   [2,3,4]])
mat2=torch.tensor([[2,3,4],
                   [3,5,6],
                   [43,34,4]])

torch.matmul(mat1,mat2)

CPU times: user 2.25 ms, sys: 0 ns, total: 2.25 ms
Wall time: 5.08 ms


tensor([[137, 115,  28],
        [185, 157,  42]])

In [42]:
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [43]:
#to find the positon of the min element in the tensor
x.argmin()

tensor(0)

In [44]:
#to find the positon of the min element in the tensor
x.argmax()

tensor(9)

In [45]:
#respahing the tensor

#we have to take care about the dimension.when we change the shape we have to take care about its number of the elements

import torch
x=torch.arange(0.,24.)
print(x,x.shape)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]) torch.Size([24])


In [46]:
#respahing the tensor
x_reshaped=x.reshape(2,2,6)
x_reshaped

tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.]],

        [[12., 13., 14., 15., 16., 17.],
         [18., 19., 20., 21., 22., 23.]]])

In [47]:
#Changing the view

#it can't change the orignal

#if we changes z then x will changes because views shares same memory with the original tensor

z=x.view(2,6,2)
print(z)

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.],
         [16., 17.],
         [18., 19.],
         [20., 21.],
         [22., 23.]]])


In [48]:
#here we changes the value of z and we observe that the memory of x automatically changes.
#they share same memory thats why when we change the monory of z ,x(original memory var) value also changes.

z[0][0][1]=9
print(x)

tensor([ 0.,  9.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])


In [49]:
#stack tensor on the top of each other
new_x=torch.tensor([[1,2,3],
                    [3,45,6],
                    [4,3,5]])

new_x.ndim

2

In [50]:
new_x_stacked=torch.stack([new_x],dim=-2)
new_x_stacked

tensor([[[ 1,  2,  3]],

        [[ 3, 45,  6]],

        [[ 4,  3,  5]]])

In [51]:
#Stacking :-
#1.vstack(verical stack):-it add the second tensor in vericaly

tensor1=torch.tensor([[1,2,3,4],
                      [5,3,2,1],
                      [3,3,2,1]]
                     )
tensor2=torch.tensor([[2,3,4,5],
                      [6,7,7,8],
                      [9,3,21,1],
                      [2,3,1,3]]
                     )
torch.vstack((tensor1,tensor2))

tensor([[ 1,  2,  3,  4],
        [ 5,  3,  2,  1],
        [ 3,  3,  2,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  7,  8],
        [ 9,  3, 21,  1],
        [ 2,  3,  1,  3]])

In [52]:
#Hstack(horizontal stack):-To add the second tensor in the horizontal direction
tensor3=torch.tensor([[5,4,3,1],
                      [3,4,5,6]])

tensor4=torch.tensor([[4,3,5,12],
                      [4,5,6,7]])

torch.hstack((tensor3,tensor4))

tensor([[ 5,  4,  3,  1,  4,  3,  5, 12],
        [ 3,  4,  5,  6,  4,  5,  6,  7]])

In [53]:
#torch.squeeze() - remove all the single dimension from a targert tensor

torch_noname=torch.zeros(2,1,2,1,3)
print(f"size of the tensor before squeez method{torch_noname}")
y=torch.squeeze(torch_noname)
print(f"size of the tensor before squeez method{y}")

size of the tensor before squeez methodtensor([[[[[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]]]]])
size of the tensor before squeez methodtensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [54]:
y1=torch.squeeze(torch_noname,1)
print(f"before parameter{torch_noname,torch_noname.size()}")
print(f"y1 when parameter passes as 1 output will be {y1.size()}")

before parameter(tensor([[[[[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]]]]]), torch.Size([2, 1, 2, 1, 3]))
y1 when parameter passes as 1 output will be torch.Size([2, 2, 1, 3])


In [55]:
y2=torch.squeeze(torch_noname,1)
print(f"y2 value when patameter is 0{y2.size()}")

y2 value when patameter is 0torch.Size([2, 2, 1, 3])


In [56]:
#torch.unsqueeze()- add one dimension at the a specific location in the targeted tensor

In [57]:
y_unsqueezed=y2.unsqueeze(dim=1)
print(f"before parameter{torch_noname,torch_noname.size()}")
print(f"The usqueezed tensor is {y_unsqueezed,y_unsqueezed.size()}")

before parameter(tensor([[[[[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]]]]]), torch.Size([2, 1, 2, 1, 3]))
The usqueezed tensor is (tensor([[[[[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]]]]]), torch.Size([2, 1, 2, 1, 3]))


In [58]:
y1=torch.zeros([2])
y2=y1.unsqueeze(dim=0)
y2.size()

torch.Size([1, 2])

In [59]:
#torch.permute()-rearranges the dimensions of a target tensor in a specified order

tensor_per=torch.ones([2,1,3,3])
print(f"before tensor is {tensor_per} size of the tensor is {tensor_per.size()}")
permuted_tensor=torch.permute(tensor_per,(2,3,0,1))
# in the above tensor the first dim is changes with the 2nd dim of the inintial tensor and the first dim is changes with the div 3 and the third tensor is changes with the zeroth dim vice varsa
print(f"permuted tensor is {permuted_tensor} size of the tensor is {permuted_tensor.size()}")

before tensor is tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]]) size of the tensor is torch.Size([2, 1, 3, 3])
permuted tensor is tensor([[[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]]]) size of the tensor is torch.Size([3, 3, 2, 1])


 TENSORS with NumPy Arrays

In [60]:
import numpy as np
array=np.arange(1.0,9.0)
print(f"array is {array} and type is {array.dtype}")
tensor_Arr=torch.from_numpy(array)
print(f"tensor using np array {tensor_Arr}")

array is [1. 2. 3. 4. 5. 6. 7. 8.] and type is float64
tensor using np array tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


In [61]:
# if we change the value of the array to something else then it cant effect the tensor
array=array+1
print(f"Array is {array}")
print(f"tensor ={tensor_Arr}")

Array is [2. 3. 4. 5. 6. 7. 8. 9.]
tensor =tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


In [62]:
#tensor to Numpy

tensor=torch.zeros(1,3)
print(f"tensor dtype is {tensor.dtype}")
numpy_tensor=tensor.numpy()
print(f"the numpy tensor is {numpy_tensor} and the size of the numpy tensor is {numpy_tensor.dtype}")

tensor dtype is torch.float32
the numpy tensor is [[0. 0. 0.]] and the size of the numpy tensor is float32


In [63]:
tensor=tensor+1

print(tensor)

print(f"tensor after numpy{numpy_tensor}")

tensor([[1., 1., 1.]])
tensor after numpy[[0. 0. 0.]]


In [64]:
import torch
random_tensor1=torch.rand(3,4)
random_tensor2=torch.rand(3,4)
print(random_tensor1)
print(random_tensor2)
print(random_tensor1==random_tensor2)


tensor([[9.8266e-01, 2.6012e-01, 9.4926e-04, 4.1946e-01],
        [3.4071e-01, 8.4222e-01, 8.6085e-01, 7.6651e-01],
        [3.9291e-01, 4.7423e-01, 2.9073e-01, 2.8375e-01]])
tensor([[0.7203, 0.6707, 0.5716, 0.2876],
        [0.0891, 0.7672, 0.3267, 0.1578],
        [0.9270, 0.4169, 0.8174, 0.6805]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [65]:
# lets make some random but reproducible tensor
import torch

#Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_a=torch.rand(3,4,6)
torch.manual_seed(RANDOM_SEED)
random_tensor_b=torch.rand(3,4,6)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
         [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090],
         [0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895]],

        [[0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447],
         [0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958],
         [0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666]]])
tensor([[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
         [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588, 0.1994, 0.5472

In [66]:
torch.manual_seed(4)
tensor=torch.rand(2,3,4)
torch.manual_seed(4)
tensor1=torch.rand(2,3,4)
print(tensor)
print(tensor1)
print(tensor==tensor1)

tensor([[[0.5596, 0.5591, 0.0915, 0.2100],
         [0.0072, 0.0390, 0.9929, 0.9131],
         [0.6186, 0.9744, 0.3189, 0.2148]],

        [[0.9263, 0.4735, 0.5949, 0.7956],
         [0.7635, 0.2137, 0.3066, 0.0386],
         [0.5220, 0.3207, 0.6074, 0.5233]]])
tensor([[[0.5596, 0.5591, 0.0915, 0.2100],
         [0.0072, 0.0390, 0.9929, 0.9131],
         [0.6186, 0.9744, 0.3189, 0.2148]],

        [[0.9263, 0.4735, 0.5949, 0.7956],
         [0.7635, 0.2137, 0.3066, 0.0386],
         [0.5220, 0.3207, 0.6074, 0.5233]]])
tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])


# **Random seeds:-**
if we set seed to 42 then it store or hold the value of the random number and when we the use the same when we call the random seed as the next squence .

In [67]:
import torch
torch.cuda.is_available()

False

In [68]:
#if there are gpu the use the gpu if not then use the cpu

device="cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [69]:
#counting the number of devices
torch.cuda.device_count()

0

In [70]:
#create a tensor (default on the cpu)

tensor =torch.tensor([1,2,3,4])
print(tensor ,tensor.device)

tensor([1, 2, 3, 4]) cpu


In [71]:
tensor_on_gpu=tensor.to(device)
print(tensor_on_gpu)

tensor([1, 2, 3, 4])


In [72]:
#if we want to use numpy then we have to change the device type to cpu
tensor_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3, 4])

In [73]:
 #2.Create a random tensor with shape (7, 7).

 import torch
 tensor_random=torch.rand([7,7])
 print(tensor_random)

tensor([[9.2627e-01, 5.4306e-01, 7.5057e-01, 6.5778e-01, 9.4361e-01, 2.9215e-01,
         9.1749e-01],
        [8.5862e-01, 3.0044e-01, 8.0649e-01, 9.6225e-01, 2.1729e-01, 3.0497e-01,
         8.4205e-01],
        [9.0316e-01, 6.3190e-01, 6.5354e-01, 8.7033e-01, 9.3819e-01, 1.8377e-01,
         2.9433e-01],
        [9.2098e-01, 7.7006e-01, 2.6540e-01, 3.3035e-01, 9.8522e-01, 1.8684e-01,
         8.2164e-01],
        [7.9014e-01, 2.0476e-02, 8.7905e-04, 6.6599e-01, 7.4532e-01, 9.4320e-01,
         5.6163e-01],
        [8.3921e-01, 1.4466e-01, 7.9846e-01, 1.8326e-02, 8.2572e-01, 5.5421e-01,
         8.0885e-01],
        [6.9751e-01, 1.5410e-01, 5.0519e-01, 5.6324e-01, 5.7188e-01, 6.2222e-02,
         2.4745e-01]])


In [74]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
#(hint: you may have to transpose the second tensor).

first_tensor=torch.rand([1,7])
second_tensor=torch.rand([1,7])

y=torch.transpose(second_tensor,0,1)

matrix_multiplication=torch.matmul(first_tensor,y)
print(matrix_multiplication)

tensor([[1.7051]])


In [75]:
#Set the random seed to 0 and do exercises 2 & 3 over again

import torch

random_seed=0
torch.manual_seed(random_seed)
tensor_random=torch.rand([7,7])
print(tensor_random)
torch.manual_seed(random_seed)
first_tensor=torch.rand([1,7])
torch.manual_seed(random_seed)
second_tensor=torch.rand([1,7])

y=torch.transpose(second_tensor,0,1)

matrix_multiplication=torch.matmul(first_tensor,y)
print(matrix_multiplication)
print(f"tensor 1 is :-{first_tensor} and tensor 2 is {y}")




tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[1.5985]])
tensor 1 is :-tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]) and tensor 2 is tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])
